#!/usr/bin/env bash

reset="\e[m"
boldgreen="\e[1;32m"
boldred="\033[1;31m"

if [ -z "$1" ]; then
    echo -e "${boldred}Ошибка: укажите приложение${reset}"
    exit 1
fi

if command -v flatpak > /dev/null 2>&1; then
    echo -e "${boldgreen}Flatpak >${reset}"
    flatpak search --columns=application,name,version,remotes "$1"
fi
if command -v snap > /dev/null 2>&1; then
    echo -e "${boldgreen}Snap >${reset}"
    if [ -z "$(snap find "$1" 2> /dev/null | awk '{printf "%-37s %-10s\n", $1, $2}')" ]; then
        echo "Совпадений не найдено"
    else
        snap find "$1" 2> /dev/null | awk '{printf "%-37s %-10s\n", $1, $2}'
    fi
fi
if command -v apt-cache > /dev/null 2>&1; then
    echo -e "${boldgreen}Репозитории >${reset}"
    if [ -z "$(sudo apt-cache search "$1")" ]; then
        echo "Совпадений не найдено"
    else
        sudo apt-cache search "$1"
    fi
fi
